### ISSUE TITLE
Which USB C Connector is used ? 

### ISSUE THREAD

**Issue by Thore-Krug** [sparkfun/RedBoard_Artemis_Nano#2]
I wanted to know which USB C Connector was used on the Board and opened the Design Files but there is no info on the Specific USB Connector used.   I also noted that the libary used for the connector was not included in the Design Files.  

Signed off by: Thore Krug opensource[at]thorekrug.de

**Comment by nseidle** [comment]
[This one](https://www.sparkfun.com/products/15111) from BSC.

**Comment by Thore-Krug** [comment]
Thank you
